### ISSUE TITLE
Problems installing with python >=3.11

### ISSUE THREAD

**Issue by JohanWinther** [maartenbreddels/per4m#10]
Hi, I'd like to use this `perf2trace` but I'm having problems installing `per4m` on python versions >=3.11 (3.10 works fine).

Here is the error message when installing with `uv` on python `3.12.8`:

```plaintext
$ uv add per4m
Resolved 110 packages in 81ms
  × Failed to build `per4m==0.1.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      copying per4m/__init__.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/example1.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/perf2trace.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/example4.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/giltracer-bcc.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/example0.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/cellmagic.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/offgil.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/example2.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/__main__.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/bla.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/record.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/giltracer.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/perfutils.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/trace.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/script.py -> build/lib.linux-x86_64-cpython-312/per4m
      copying per4m/example3.py -> build/lib.linux-x86_64-cpython-312/per4m
      running build_ext
      building 'per4m.pytrace' extension
      c++ -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG
      -g -O3 -Wall -fPIC -fPIC -I/home/johan/.cache/uv/builds-v0/.tmpVAQWcm/include
      -I/home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12 -c per4m/probes.cpp -o
      build/temp.linux-x86_64-cpython-312/per4m/probes.o -g -O1
      c++ -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG
      -g -O3 -Wall -fPIC -fPIC -I/home/johan/.cache/uv/builds-v0/.tmpVAQWcm/include
      -I/home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12 -c per4m/pytrace.cpp -o
      build/temp.linux-x86_64-cpython-312/per4m/pytrace.o -g -O1

      [stderr]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "/home/johan/.cache/uv/builds-v0/.tmpVAQWcm/lib/python3.12/site-packages/setuptools_scm/_integration/pyproject_reading.py",
      line 36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      KeyError: 'setuptools_scm'
      per4m/pytrace.cpp: In function ‘int pytrace_trace(PyObject*, PyFrameObject*, int, PyObject*)’:
      per4m/pytrace.cpp:20:31: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
         20 |     PyCodeObject *code = frame->f_code;
            |                               ^~
      In file included from /home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12/Python.h:42,
                       from per4m/pytrace.cpp:1:
      /home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12/pytypedefs.h:22:16: note: forward declaration
      of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      per4m/pytrace.cpp:23:42: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
         23 |     lineno = PyCode_Addr2Line(code, frame->f_lasti);
            |                                          ^~
      /home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12/pytypedefs.h:22:16: note: forward declaration
      of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      per4m/pytrace.cpp:32:31: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
         32 |     PyCodeObject *code = frame->f_code;
            |                               ^~
      /home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12/pytypedefs.h:22:16: note: forward declaration
      of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      per4m/pytrace.cpp:35:42: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
         35 |     lineno = PyCode_Addr2Line(code, frame->f_lasti);
            |                                          ^~
      /home/johan/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/include/python3.12/pytypedefs.h:22:16: note: forward declaration
      of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/c++' failed with exit code 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `per4m` (v0.1.0) was included because `apc:dev` (v0.0.1) depends on `per4m`
```

It seems like `PyFrameObject` has been deprecated in favour of `_PyInterpreterFrame*` according to [this thread](https://discuss.python.org/t/no-obvious-way-of-getting-pyframeobject-inside-a-frame-evaluation-function-in-python-3-11/25966). I get the same problem installing with pip.

What I actually want to do is to only use the `perf2trace` functionality, so I installed the package without building, but I still had to patch `per4m/__init__.py` to use `importlib.metadata.version` instead of `pkg_resources.get_distribution` to get it working with `3.12.8`.

Do you mind me asking if you are planning on supporting >=3.11 (or should I make my small patch somewhat permanent in my setup)?
